FROM {{ parrotos_docker_image }}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade
{% if parrotos_packges is defined %}
{% for packges in parrotos_packges %} 
RUN apt-get update && apt-get install -y \
    {{ packges }}
{% endfor %}
{% endif %}